-- Per-scan SBOMs (CycloneDX + SPDX), generated by Trivy at scan time from the
-- authenticated checkout. Kept in a side table so large documents never bloat
-- the hot scans row (Phase 2E Task 3).
CREATE TABLE IF NOT EXISTS scan_sboms (
    scan_id      UUID PRIMARY KEY REFERENCES scans(id) ON DELETE CASCADE,
    cyclonedx    TEXT,
    spdx         TEXT,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
